# Traffic Accident logistische regressie uitwerking

**Auteurs:** Lars Tovar  
**Opleiding:** HBO-ICT, Hogeschool Windesheim  
**Vak:** Machine Learning

---
## Onderzoeksvraag

> **Kunnen we met Machine Learning voorspellen of een verkeersongeval 'Slight', 'Serious' of 'Fatal' is, op basis van omgevings- en wegkenmerken uit de UK Road Safety dataset (2005-2017)?**

### Deelvragen

1. Welke omgevings- en wegkenmerken zijn beschikbaar in de dataset?
2. Welke features correleren het sterkst met de ernst van een ongeval?
3. Welk ML-algoritme presteert het beste voor deze classificatietaak?

---
## 1. Imports

In [9]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, balanced_accuracy_score
import numpy as np
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold

---
## 2. Data Laden

In [10]:
X_train_df = pd.read_csv("train_set.csv")
X_val_df   = pd.read_csv("validation_set.csv")
X_test_df  = pd.read_csv("test_set.csv")

y_train = pd.read_csv("y_train.csv").squeeze()  #variables inlezen en omzetten voor sklearn compatibility
y_val   = pd.read_csv("y_val.csv").squeeze()
y_test  = pd.read_csv("y_test.csv").squeeze()

---
## 3. Random forest  

Met class imbalance meegerekent.

In [11]:
rf = RandomForestClassifier(
    n_estimators=400,
    random_state=42,
    n_jobs=-1,
    class_weight="balanced",  # class imbalance verbeteren
    max_features="sqrt"
)

rf.fit(X_train_df, y_train)


RandomForestClassifier(class_weight='balanced', n_estimators=400, n_jobs=-1,
                       random_state=42)

---
## 4. Evaluatie of validation

In [12]:
y_val_pred = rf.predict(X_val_df) #voorspellingen op de validation set

print("VAL Balanced accuracy:", balanced_accuracy_score(y_val, y_val_pred))
print("\nVAL Classification report:\n")
print(classification_report(y_val, y_val_pred, digits=4))
print("\nVAL Confusion matrix:\n")
print(confusion_matrix(y_val, y_val_pred)) #confusionmatrix om te zien welke klasses vaak confued worden

VAL Balanced accuracy: 0.33819223729297904

VAL Classification report:

              precision    recall  f1-score   support

           0     0.8639    0.9944    0.9246     17268
           1     0.1681    0.0080    0.0154      2485
           2     0.6000    0.0121    0.0238       247

    accuracy                         0.8597     20000
   macro avg     0.5440    0.3382    0.3212     20000
weighted avg     0.7742    0.8597    0.8005     20000


VAL Confusion matrix:

[[17171    96     1]
 [ 2464    20     1]
 [  241     3     3]]


---
## 5. Tuning

In [13]:
param_dist = {
    "n_estimators": [200], #parameters voor de randomsearch grid
    "max_depth": [10, 20, 30],
    "min_samples_split": [2, 5, 10],
    "max_features": ["sqrt", "log2", 0.5],
    "bootstrap": [True],
}

cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

rf_base = RandomForestClassifier(
    random_state=42,
    n_jobs=-1,              #ik gebruik hier alle cores ivm grootte dataset
    class_weight="balanced" #rekening houden met onevenwichtige klasses
)

search = RandomizedSearchCV( 
    estimator=rf_base,
    param_distributions=param_dist,
    n_iter=25,              # aantal keren om te testen
    scoring="f1_macro",     # eerlijk voor alle klassen houden
    cv=cv,
    n_jobs=-1,              #gebruiken alle cores bij de search ook om volledige search in redelijke tijd te doen
    random_state=42,
    verbose=1
)
    
search.fit(X_train_df, y_train)

print("Best params:", search.best_params_) 
print("Best CV f1_macro:", search.best_score_) # beste parameters en scoren output
 
best_rf = search.best_estimator_ # beste model opslaan


Fitting 3 folds for each of 25 candidates, totalling 75 fits


c:\Users\koen1\OneDrive\Desktop\Traffic Accident\.env\Lib\site-packages\joblib\externals\loky\process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


Best params: {'n_estimators': 200, 'min_samples_split': 10, 'max_features': 'log2', 'max_depth': 20, 'bootstrap': True}
Best CV f1_macro: 0.37039575361811167


---
## 5. Evaluation model after tuning

In [14]:
y_val_pred = best_rf.predict(X_val_df)

print("VAL Balanced accuracy:", balanced_accuracy_score(y_val, y_val_pred))
print("\nVAL Classification report:\n")
print(classification_report(y_val, y_val_pred, digits=4)    )
print("\nVAL Confusion matrix:\n")
print(confusion_matrix(y_val, y_val_pred))


VAL Balanced accuracy: 0.39531461469689716

VAL Classification report:

              precision    recall  f1-score   support

           0     0.8804    0.8507    0.8653     17268
           1     0.1826    0.1976    0.1898      2485
           2     0.0544    0.1377    0.0780       247

    accuracy                         0.7608     20000
   macro avg     0.3725    0.3953    0.3777     20000
weighted avg     0.7835    0.7608    0.7716     20000


VAL Confusion matrix:

[[14690  2138   440]
 [ 1843   491   151]
 [  153    60    34]]


---
## 6. Last evaluation

In [15]:
y_test_pred = best_rf.predict(X_test_df)

print("TEST Balanced accuracy:", balanced_accuracy_score(y_test, y_test_pred))
print("\nTEST Classification report:\n")
print(classification_report(y_test, y_test_pred, digits=4))
print("\nTEST Confusion matrix:\n")
print(confusion_matrix(y_test, y_test_pred))


TEST Balanced accuracy: 0.39528443735208735

TEST Classification report:

              precision    recall  f1-score   support

           0     0.8820    0.8514    0.8664     17269
           1     0.1908    0.2089    0.1995      2484
           2     0.0508    0.1255    0.0723       247

    accuracy                         0.7627     20000
   macro avg     0.3745    0.3953    0.3794     20000
weighted avg     0.7859    0.7627    0.7738     20000


TEST Confusion matrix:

[[14703  2138   428]
 [ 1814   519   151]
 [  153    63    31]]


---
## 7. Feature importance  

Welke features waren het belangrijkst?

In [16]:
importances = pd.Series(best_rf.feature_importances_, index=X_train_df.columns)
top20 = importances.sort_values(ascending=False).head(20)
print(top20)

Longitude                                        0.151041
Latitude                                         0.149439
Hour                                             0.122248
DayOfWeek_fromDate                               0.080406
Speed_limit                                      0.062303
Urban_or_Rural_Area_Urban                        0.032075
Pedestrian_Crossing-Physical_Facilities          0.027160
Light_Conditions_Daylight                        0.022402
1st_Road_Class_Unclassified                      0.019886
Road_Type_Single carriageway                     0.019562
Road_Surface_Conditions_Dry                      0.017204
Road_Surface_Conditions_Wet or damp              0.016917
1st_Road_Class_B                                 0.016246
Light_Conditions_Darkness - lights lit           0.015657
Weather_Conditions_Fine no high winds            0.015403
2nd_Road_Class_Unclassified                      0.013817
1st_Road_Class_C                                 0.013722
Junction_Detai